title: IntScription
description: My journey building projects, AI apps, and refining my craft in public.
author: Kartik Sanil
theme: minima
baseurl: "/devlog"
url: "https://intscription.github.io"

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

minima:
  social_links:
    github: https://github.com/IntScription
    youtube: https://www.youtube.com/@idkythisisme
  header_pages:
    - index.md
    - archive.md

sass:
  sass_dir: assets/css
  style: compressed

exclude:
  - README.md
  - .gitignore
  - .DS_Store
  - notes

include:
  - logs

defaults:
  - scope:
      path: "logs"
    values:
      title: ""
      sitemap: false

